sonar.projectKey=amteamx_job-center
sonar.organization=amteamx

# This is the name and version displayed in the SonarCloud UI.
# sonar.projectName=Job Center Management System
# sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=implementations/frontend/src,implementations/backend/src

# Encoding of the source code. Default is default system encoding
# sonar.sourceEncoding=UTF-8

# Exclude folders from analysis
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/package-lock.json, implementations/backend/src/prisma/migrations/**/*.sql
